# Generated by Django 5.0.6 on 2024-07-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PickUpLocation', models.CharField(max_length=100)),
                ('DropLocation', models.CharField(max_length=100)),
                ('PriceMAD', models.IntegerField()),
            ],
        ),
    ]
